"""Pipeline orchestrator: detect -> convert -> validate -> store -> ingest.

Conversion and validation are CPU/IO-bound sync operations. They run in a
thread via asyncio.to_thread() to avoid blocking the event loop (which would
freeze SSE streams and health checks during processing).
"""

import asyncio
import os
import tempfile

import httpx

from src.config import get_settings
from src.models import Dataset, Job, JobStatus, FormatPair, DatasetType, ValidationCheck
from src.services.detector import detect_format, validate_magic_bytes
from src.services.storage import StorageService
from src.services import stac_ingest, vector_ingest, pmtiles_ingest


def get_credits(format_pair: FormatPair, use_pmtiles: bool = False) -> list[dict]:
    """Return the credits list for a given conversion path."""
    credits = []

    if format_pair == FormatPair.GEOTIFF_TO_COG:
        credits.append({"tool": "rio-cogeo", "url": "https://github.com/cogeotiff/rio-cogeo", "role": "Converted by"})
    elif format_pair == FormatPair.NETCDF_TO_COG:
        credits.append({"tool": "xarray", "url": "https://xarray.dev", "role": "Read by"})
        credits.append({"tool": "rio-cogeo", "url": "https://github.com/cogeotiff/rio-cogeo", "role": "Converted by"})
    elif format_pair in (FormatPair.SHAPEFILE_TO_GEOPARQUET, FormatPair.GEOJSON_TO_GEOPARQUET):
        credits.append({"tool": "GeoPandas", "url": "https://geopandas.org", "role": "Converted by"})

    if format_pair.dataset_type == DatasetType.RASTER:
        credits.append({"tool": "TiTiler", "url": "https://developmentseed.org/titiler", "role": "Tiles served by"})
        credits.append({"tool": "pgSTAC", "url": "https://github.com/stac-utils/pgstac", "role": "Cataloged by"})
    elif use_pmtiles:
        credits.append({"tool": "tippecanoe", "url": "https://github.com/felt/tippecanoe", "role": "Tiles generated by"})
        credits.append({"tool": "PMTiles", "url": "https://github.com/protomaps/PMTiles", "role": "Tiles served by"})
    else:
        credits.append({"tool": "tipg", "url": "https://github.com/developmentseed/tipg", "role": "Tiles served by"})

    credits.append({"tool": "MapLibre", "url": "https://maplibre.org", "role": "Map rendered by"})
    return credits


def _extract_bounds(output_path: str, dataset_type: DatasetType) -> list[float]:
    """Extract [west, south, east, north] bounds in EPSG:4326."""
    if dataset_type == DatasetType.RASTER:
        import rasterio
        from rasterio.warp import transform_bounds
        with rasterio.open(output_path) as src:
            if src.crs and str(src.crs) != "EPSG:4326":
                return list(transform_bounds(src.crs, "EPSG:4326", *src.bounds))
            b = src.bounds
            return [b.left, b.bottom, b.right, b.top]
    else:
        import geopandas as gpd
        gdf = gpd.read_parquet(output_path)
        b = gdf.total_bounds  # [minx, miny, maxx, maxy]
        return [float(b[0]), float(b[1]), float(b[2]), float(b[3])]


def _extract_band_count(output_path: str) -> int:
    """Return the number of bands in a raster file."""
    import rasterio
    with rasterio.open(output_path) as src:
        return src.count


def _extract_feature_stats(parquet_path: str) -> tuple[int, list[str]]:
    """Return (feature_count, geometry_types) from a GeoParquet file.

    geometry_types is sorted by frequency, most common first.
    """
    import geopandas as gpd
    gdf = gpd.read_parquet(parquet_path)
    feature_count = len(gdf)
    if feature_count == 0:
        return 0, []
    geometry_types = gdf.geometry.geom_type.value_counts().index.tolist()
    return feature_count, geometry_types


def _extract_zoom_range_raster(cog_path: str) -> tuple[int, int]:
    """Derive min/max tile zoom from a COG's native resolution and overview count."""
    import math
    import rasterio
    from rasterio.crs import CRS
    from rasterio.warp import transform_bounds

    with rasterio.open(cog_path) as src:
        if src.crs and not src.crs.is_geographic:
            bounds = transform_bounds(src.crs, CRS.from_epsg(4326), *src.bounds)
        else:
            b = src.bounds
            bounds = (b.left, b.bottom, b.right, b.top)

        width_deg = bounds[2] - bounds[0]
        if width_deg <= 0 or src.width <= 0:
            return 0, 0

        native_pixel_deg = width_deg / src.width
        max_zoom = max(0, min(20, round(math.log2(360.0 / (native_pixel_deg * 256)))))
        n_overviews = len(src.overviews(1))
        min_zoom = max(0, max_zoom - n_overviews)
        return min_zoom, max_zoom


def _detect_use_pmtiles(output_path: str) -> bool:
    """Return True if the dataset contains polygon or line features."""
    import geopandas as gpd
    gdf = gpd.read_parquet(output_path)
    return bool(
        gdf.geom_type.isin(
            ["Polygon", "MultiPolygon", "LineString", "MultiLineString"]
        ).any()
    )


async def run_pipeline(job: Job, input_path: str, datasets_store: dict) -> None:
    """Execute the full conversion pipeline. Updates job status in-place.

    This function is called from a BackgroundTask. It catches all exceptions
    and sets job.status = FAILED with an error message rather than crashing.
    """
    settings = get_settings()
    storage = StorageService()

    try:
        # Stage 1: Scan
        job.status = JobStatus.SCANNING
        format_pair = detect_format(job.filename)
        job.format_pair = format_pair
        validate_magic_bytes(input_path, format_pair)
        original_file_size = os.path.getsize(input_path)

        # Upload raw file to S3
        storage.upload_raw(input_path, job.dataset_id, job.filename)

        # Stage 2: Convert
        job.status = JobStatus.CONVERTING

        if format_pair.dataset_type == DatasetType.RASTER:
            out_filename = os.path.splitext(job.filename)[0] + ".tif"
        else:
            out_filename = os.path.splitext(job.filename)[0] + ".parquet"

        with tempfile.TemporaryDirectory() as tmpdir:
            output_path = os.path.join(tmpdir, out_filename)

            await asyncio.to_thread(_import_and_convert, format_pair, input_path, output_path)

            # Stage 3: Validate
            job.status = JobStatus.VALIDATING
            check_results = await asyncio.to_thread(_import_and_validate, format_pair, input_path, output_path)
            job.validation_results = [
                ValidationCheck(name=c.name, passed=c.passed, detail=c.detail)
                for c in check_results
            ]

            failed = [c for c in check_results if not c.passed]
            if failed:
                job.status = JobStatus.FAILED
                job.error = f"{len(failed)} validation check(s) failed"
                return

            # Extract bounds for auto-zoom
            bounds = await asyncio.to_thread(_extract_bounds, output_path, format_pair.dataset_type)

            # Extract band count for rasters (used by the frontend to determine colormap eligibility)
            band_count = None
            if format_pair.dataset_type == DatasetType.RASTER:
                band_count = await asyncio.to_thread(_extract_band_count, output_path)

            # Raster converted_file_size: output_path IS the COG at this point
            converted_file_size = os.path.getsize(output_path) if format_pair.dataset_type == DatasetType.RASTER else None

            # Extract feature stats (vector only)
            feature_count = None
            geometry_types = None
            if format_pair.dataset_type == DatasetType.VECTOR:
                feature_count, geometry_types = await asyncio.to_thread(
                    _extract_feature_stats, output_path
                )

            # Extract zoom range (vector PMTiles path sets these below via ingest_pmtiles)
            min_zoom = None
            max_zoom = None

            # Stage 4: Ingest
            job.status = JobStatus.INGESTING

            converted_key = storage.upload_converted(output_path, job.dataset_id, out_filename)
            s3_href = storage.get_s3_uri(converted_key)

            use_pmtiles = False
            if format_pair.dataset_type == DatasetType.RASTER:
                tile_url = await stac_ingest.ingest_raster(
                    job.dataset_id, output_path, s3_href, job.filename,
                )
                min_zoom, max_zoom = await asyncio.to_thread(
                    _extract_zoom_range_raster, output_path
                )
            else:
                use_pmtiles = await asyncio.to_thread(_detect_use_pmtiles, output_path)
                if use_pmtiles:
                    tile_url, min_zoom, max_zoom, converted_file_size = await asyncio.to_thread(
                        pmtiles_ingest.ingest_pmtiles, job.dataset_id, output_path,
                    )
                else:
                    tile_url = await asyncio.to_thread(
                        vector_ingest.ingest_vector, job.dataset_id, output_path,
                    )
                    await _wait_for_tipg_collection(job.dataset_id)

        # Stage 5: Ready
        job.status = JobStatus.READY

        dataset = Dataset(
            id=job.dataset_id,
            filename=job.filename,
            dataset_type=format_pair.dataset_type,
            format_pair=format_pair,
            tile_url=tile_url,
            bounds=bounds,
            band_count=band_count,
            original_file_size=original_file_size,
            converted_file_size=converted_file_size,
            feature_count=feature_count,
            geometry_types=geometry_types,
            min_zoom=min_zoom,
            max_zoom=max_zoom,
            stac_collection_id=f"sandbox-{job.dataset_id}" if format_pair.dataset_type == DatasetType.RASTER else None,
            pg_table=vector_ingest.build_table_name(job.dataset_id) if (
                format_pair.dataset_type == DatasetType.VECTOR and not use_pmtiles
            ) else None,
            validation_results=job.validation_results,
            credits=get_credits(format_pair, use_pmtiles=use_pmtiles),
            created_at=job.created_at,
        )
        datasets_store[job.dataset_id] = dataset

    except Exception as e:
        job.status = JobStatus.FAILED
        job.error = str(e)


async def _wait_for_tipg_collection(dataset_id: str, timeout: float = 30.0) -> None:
    """Poll tipg until it has discovered the new collection, or timeout."""
    settings = get_settings()
    table = vector_ingest.build_table_name(dataset_id)
    collection_id = f"public.{table}"
    url = f"{settings.vector_tiler_url}/collections/{collection_id}"
    deadline = asyncio.get_event_loop().time() + timeout
    async with httpx.AsyncClient() as client:
        while asyncio.get_event_loop().time() < deadline:
            try:
                resp = await client.get(url, headers={"Accept": "application/json"}, timeout=5.0)
                if resp.status_code == 200:
                    return
            except Exception:
                pass
            await asyncio.sleep(1.0)


def _import_and_convert(format_pair: FormatPair, input_path: str, output_path: str) -> None:
    """Import the appropriate cng-toolkit converter and run it."""
    if format_pair == FormatPair.GEOTIFF_TO_COG:
        from geotiff_to_cog import convert
    elif format_pair == FormatPair.SHAPEFILE_TO_GEOPARQUET:
        from shapefile_to_geoparquet import convert
    elif format_pair == FormatPair.GEOJSON_TO_GEOPARQUET:
        from geojson_to_geoparquet import convert
    elif format_pair == FormatPair.NETCDF_TO_COG:
        from netcdf_to_cog import convert
    else:
        raise ValueError(f"Unknown format pair: {format_pair}")

    convert(input_path, output_path, verbose=True)


def _import_and_validate(format_pair: FormatPair, input_path: str, output_path: str) -> list:
    """Import the appropriate cng-toolkit validator and run checks."""
    if format_pair == FormatPair.GEOTIFF_TO_COG:
        from geotiff_to_cog import run_checks
    elif format_pair == FormatPair.SHAPEFILE_TO_GEOPARQUET:
        from shapefile_to_geoparquet import run_checks
    elif format_pair == FormatPair.GEOJSON_TO_GEOPARQUET:
        from geojson_to_geoparquet import run_checks
    elif format_pair == FormatPair.NETCDF_TO_COG:
        from netcdf_to_cog import run_checks
    else:
        raise ValueError(f"Unknown format pair: {format_pair}")

    return run_checks(input_path, output_path)
